version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    # Если .env нет, можно передать напрямую (но лучше через .env)
    environment:
      - API_TOKEN=${API_TOKEN}
